version: '3'
services:
    app:
        container_name: mock-rest-api
        build: .
        ports:
            - "3000:3000"
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27107"
        volumes:
            - './data:/data/db'	
#         volumes:
#             - mongodata:/data/db
# volumes:
#     mongodata:
